language: node_js
node_js:
- '5.0.0'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- export CXX=g++-4.8
before_script:
- npm install -g gulp
script:
- gulp ci
